import mongoose from "mongoose";

// User Schema Definition
const UserSchema = new mongoose.Schema(
  {
    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
    email: { type: String, required: true, unique: true }, // Email must be unique
    password: { type: String, required: true }, // Store hashed passwords
    resetPasswordOtp : String,
    resetPasswordExpire: Date,
  },
  {
    timestamps: true, // Automatically adds createdAt and updatedAt fields
  }
);

// TypeScript Interface for User
export interface User {
  _id: string;
  firstName: string;
  lastName: string;
  email: string;
  password: string; // Should store hashed password
  resetPasswordOtp ?: string; // Optional, used for password reset
  resetPasswordExpire?: Date; // Optional, used for password reset
  createdAt?: Date; // Optional, auto-generated by Mongoose
  updatedAt?: Date; // Optional, auto-generated by Mongoose
}

// Export the model or retrieve the existing model
export default mongoose.models.User || mongoose.model("User", UserSchema);
